# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[connections]
[connections.myconnection]
account = "KFBGAMM-MJB61345"
user = "ducounau"
password = "ilike@Bnl91"
role = "ACCOUNTADMIN"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "ANALYTICS"
